version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-sam-kms-details"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1df1hjf2lfia3"
s3_prefix = "aws-sam-kms-details"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppBucketName=\"\""
image_repositories = []
